Feature/oepcis 494 fixing issues based on hash id rules
openepcis/openepcis-epc-digitallink-translator pull request #5
Opened 2023-01-25 11:11 UTC by Aravinda93

This PR will add the methods to convert convert the identifier from they key to respective identifier associated with them such as `giai` to `8004` which is required during the pre-hash string generation in event hash generator. Also, includes some fixes to bareString, CBV vocabulary conversion and some enhancement.

This along with PR: https://github.com/openepcis/openepcis-event-hash-generator/pull/10 should fix the issue: https://github.com/openepcis/openepcis-event-hash-generator/issues/9 and many other issues in pre-hash string.

Kindly request you to approve the PR and merge.

2023-01-25 12:47 UTC, sboeckelmann requested changes

2023-01-25 12:47 UTC, sboeckelmann commented on src/main/java/io/openepcis/epc/translator/Converter.java
> +    return gs1Identifier == null || gs1Identifier.trim().equals("")
use some String util to check if it's empty

2023-01-25 12:47 UTC, sboeckelmann commented on src/main/java/io/openepcis/epc/translator/EventVocabularyFormatter.java
>    private static final String WEB_URI_PREFIX = "https://ref.gs1.org/cbv/";
these domains are also used in HashGenerator. Move to Constants and use same constants in both projects
usage in hash generator ConstantEventHashInfo
```
  protected static final String GS1_DOMAIN = "https://gs1.org/voc/";
  protected static final String GS1_COMPONENT_DOMAIN = "https://ref.gs1.org/cbv/Comp-";
```

2023-01-25 12:47 UTC, sboeckelmann commented on src/main/java/io/openepcis/epc/translator/EventVocabularyFormatter.java
> +  private final List<String> excludeSerial = List.of("/lot/", "/ser/", "/10/", "/21/");
this can be a static field

2023-01-25 12:47 UTC, sboeckelmann commented on src/main/java/io/openepcis/epc/translator/EventVocabularyFormatter.java
> +  private final Map<String, String> shortNameKeyIdentifier = new HashMap<>();
this can be a initialized statically - no need to fill in constructor

2023-01-25 12:47 UTC, sboeckelmann commented on src/main/java/io/openepcis/epc/translator/EventVocabularyFormatter.java
> +    CURIE_PREFIX_MAPPER.put("bizstep", BIZ_STEP_CURIE_PREFIX);
move to static field initialization

2023-01-25 12:47 UTC, sboeckelmann commented on src/main/java/io/openepcis/epc/translator/EventVocabularyFormatter.java
> +    shortNameKeyIdentifier.put("/gtin/", "/01/");
move to static field initialization

2023-01-27 14:58 UTC, Aravinda93 commented
@sboeckelmann 

Based on your suggestion I have modified the code accordingly. Kindly request you to review and approve the PR.

2023-01-27 15:43 UTC, sboeckelmann approved these changes

2023-01-27 15:43 UTC, merged